### ISSUE TITLE
U can breadcast to 1 device now.

### ISSUE THREAD

**Issue by malosaa** [AndBobsYourUncle/hassio-addons#48]
It is now possible to broadcast to 1 device.

Today i did find out how, i did say  hey google, broadcast/announce to kitchen. than it asked what message and it announcec only there.

But on my phone i could use a text message so the default voice speaks instead of the tts from home assistant.

**Comment by chelming** [comment]
just change your broadcast message to be "to kitchen the rest of your message"

**Comment by malosaa** [comment]
> just change your broadcast message to be "to kitchen the rest of your message"

Well i did install this add-on and can't get it to work.
I  did add the json file, and when pressing authrorisation it opens a webpage with this error:

**Comment by malosaa** [comment]
@chelming 

how does it work?

**Comment by calisro** [comment]
> @calisro does google have the ability to target a specified set of speakers when using your voice? like "broadcast to kitchen and livingroom it's lunch time"?

No.  You can hit only one at a time with a targeted 'broadcast to <speaker>'.  It would be nice if the package would allow parallel commands to run so that we can do that in a loop.  Although I do that now, it will be sequential and very delayed across multiple speakers.

```
            sequence:
              - variables:
                  speakers: |
                      {{ expand(target) | map(attribute='entity_id') | list }}
              - repeat:
                  count: '{{ speakers | count }}'
                  sequence:
                    - variables:
                        speaker: '{{ speakers[repeat.index - 1] }}'
                    - choose:
                        - conditions:
                            - condition: template
                              value_template: '{{ message | length > 0 }}'
                          sequence:
                            - service: script.turn_on
                              data:
                                variables:
                                  message: >-
                                    broadcast to {{ state_attr('' ~
                                    speaker,'friendly_name') }},
                                    {{message|default('Test Message',true) }}
                              target:
                                entity_id: script.run_ga_command
```
